language: C
sudo: required
services:
- docker

addons:
  ssh_known_hosts: $DEPLOYMENT_TARGET

env:
  - DOCKER_IMAGE_NAME="$DOCKER_REGISTRY/3r1c/docker-registry-frontend:1.0-$TRAVIS_BUILD_NUMBER"

script:
  - make compile

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
- docker build -t $DOCKER_IMAGE_NAME .
- docker push $DOCKER_IMAGE_NAME

#before_deploy:
#- openssl aes-256-cbc -K $encrypted_d3751784d1e2_key -iv $encrypted_d3751784d1e2_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
#- eval "$(ssh-agent -s)"
#- chmod 600 /tmp/deploy_rsa
#- ssh-add /tmp/deploy_rsa

#deploy:
#  - provider: script
#    script: ssh core@$DEPLOYMENT_TARGET 'docker pull $DOCKER_IMAGE_NAME && docker service update --image $DOCKER_IMAGE_NAME registry'
